CREATE TABLE `ps_product_metadata` (
  `id` bigint(18) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键 id',
  `key` varchar(64) NOT NULL DEFAULT '' COMMENT '元数据key',
  `name` varchar(64) NOT NULL DEFAULT '' COMMENT '元数据名称',
  `type` varchar(32) NOT NULL DEFAULT '' COMMENT '数据类型 string:字符串 decimal:小数 integer:整数 bool:布尔值(0或1) 5:enum',
  `range` varchar(1024) NOT NULL DEFAULT '' COMMENT '数据范围,type=string|decimal|integer时有效,例如:(0,9]代表>0且<=9;[0,+)代表>=0',
  `value_json` varchar(1024) NOT NULL DEFAULT '' COMMENT '值json,type=bool|enum时有效',
  `default_value` varchar(1024) NOT NULL DEFAULT '' COMMENT '默认值',
  `check_script` varchar(5000) NOT NULL DEFAULT '' COMMENT '校验脚本',
  `group` varchar(64) NOT NULL DEFAULT '' COMMENT '分组',
  `group_sort` int(11) NOT NULL DEFAULT '0' COMMENT '分组内顺序',
  `sort` int(11) NOT NULL DEFAULT '0' COMMENT '顺序',
  `tag` varchar(64) NOT NULL DEFAULT '' COMMENT '标签',
  `placeholder` varchar(128) NOT NULL DEFAULT '' COMMENT '界面控件输入提示 widget_type=input|textarea时有效',
  `widget_type` varchar(32) NOT NULL DEFAULT '0' COMMENT '控件类型 input:输入框 radio:单选框 select:下拉列表 checkbox:复选框 textarea:文本域',
  `web_check_script` varchar(5000) NOT NULL DEFAULT '' COMMENT '界面校验脚本',
  `desc` varchar(512) NOT NULL DEFAULT '' COMMENT '描述',
  `add_user` varchar(32) NOT NULL DEFAULT '' COMMENT '添加人',
  `modify_user` varchar(32) NOT NULL DEFAULT '' COMMENT '修改人',
  `is_delete` tinyint(4) DEFAULT '0' COMMENT '是否删除，0：正常，1：删除',
  `add_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录新增时间',
  `modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录最后一次修改时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_ps_product_metadata_key` (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='产品元数据'